export const data = [
  {
    sr_no: 1,
    name: "Which of the following is true about the anonymous inner class?",
    option1: "It has only methods",
    option2: "Objects can't be created",
    option3: "It has a fixed class name",
    option4: "It has no class name",
    answer: "It has only methods",
  },
  {
    sr_no: 2,
    name: " What do you mean by nameless objects?",
    option1: "An object created by using the new keyword.",
    option2: "An object of a superclass created in the subclass.",
    option3: "An object without having any name but having a reference.",
    option4: "An object that has no reference.",
    answer: "An object that has no reference.",
  },
  {
    sr_no: 3,
    name: "Which of the following option leads to the portability and security of Java?",
    option1: "Bytecode is executed by JVM",
    option2: "The applet makes the Java code secure and portable",
    option3: "Use of exception handling",
    option4: "Dynamic binding between objects",
    answer: "Bytecode is executed by JVM",
  },
  {
    sr_no: 4,
    name: "Which of the following is not a Java features?",
    option1: "Dynamic",
    option2: "Architecture Neutral",
    option3: "Use of pointers",
    option4: "Object-oriented",
    answer: "Dynamic",
  },
  {
    sr_no: 5,
    name: "he article referred to as a",
    option1: "Unicode escape sequence",
    option2: "Octal escape",
    option3: "Hexadecimal",
    option4: "Line feed",
    answer: "Octal escape",
  },
  {
    sr_no: 6,
    name: "____ is used to find and fix bugs in the Java programs.",
    option1: "JVM",
    option2: "JRE",
    option3: "JDK",
    option4: "JDB",
    answer: "JVM",
  },
  {
    sr_no: 7,
    name: "What is the return type of the hashCode() method in the Object class?",
    option1: "Object",
    option2: "int",
    option3: "long",
    option4: "void",
    answer: "int",
  },
  {
    sr_no: 8,
    name: "Which of the following creates a List of 3 visible items and multiple selections abled?",
    option1: "new List(false, 3)",
    option2: "new List(3, true)",
    option3: "new List(true, 3)",
    option4: "new List(3, false)",
    answer: "new List(false, 3)",
  },
  {
    sr_no: 9,
    name: "Which method of the Class.class is used to determine the name of a class represented by the class object as a String?",
    option1: "getClass()",
    option2: "intern()",
    option3: "getName()",
    option4: "toString()",
    answer: "intern()",
  },
  {
    sr_no: 10,
    name: "In which process, a local variable has the same name as one of the instance variables?",
    option1: "Serialization",
    option2: "Variable Shadowing",
    option3: "Abstraction",
    option4: "Multi-threading",
    answer: "Abstraction",
  },
];
